/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import GUI from 'lil-gui'

import { useStopAnimation, useBlendshapeAnimation } from './face_animations'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/static/models/Avatar_temp.glb')

  const stopAnim = useStopAnimation()
  const bledshapeAnim = useBlendshapeAnimation()

  const [animList, setAnimList] = useState([stopAnim, bledshapeAnim])

  const { actions, names } = useAnimations(animList, group)

  useEffect(() => {
    actions[names[props.animIndex]].reset().fadeIn(0.5).play()
    return () => actions[names[props.animIndex]].fadeOut(0.5)
  })

  // GUI
  useEffect(() => {
    const influences = nodes.Head_m_1.morphTargetInfluences
    const gui = new GUI()

    for ( const [ key, value ] of Object.entries( nodes.Head_m_1.morphTargetDictionary ) ) {
      gui.add( influences, value, 0, 1, 0.01 )
        .name( key )
        .listen( influences );
    }
    return () => gui.destroy()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -5, -0.03]} scale={6}>
        <primitive object={nodes.LeftLeg_IK} />
        <primitive object={nodes.LeftKnee_Target} />
        <primitive object={nodes.RightKnee_Target} />
        <primitive object={nodes.RightLeg_IK} />
        <primitive object={nodes.HipController} />
      </group>
      {/* <skinnedMesh
        geometry={nodes.Body.geometry}
        material={nodes.Body.material}
        skeleton={nodes.Body.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100.04}
      /> */}
      {/* <skinnedMesh
        geometry={nodes.Hand.geometry}
        material={nodes.Hand.material}
        skeleton={nodes.Hand.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100.04}
      />
      <skinnedMesh
        geometry={nodes.Arm.geometry}
        material={nodes.Arm.material}
        skeleton={nodes.Arm.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100.04}
      />
      <skinnedMesh
        geometry={nodes.Leg.geometry}
        material={nodes.Leg.material}
        skeleton={nodes.Leg.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100.04}
      />
      <skinnedMesh
        geometry={nodes.Foot.geometry}
        material={nodes.Foot.material}
        skeleton={nodes.Foot.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100.04}
      /> */}
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100.04}>
        <skinnedMesh
          name="Head_m_1"
          geometry={nodes.Head_m_1.geometry}
          material={materials['Body.001']}
          skeleton={nodes.Head_m_1.skeleton}
          morphTargetDictionary={nodes.Head_m_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="Head_m_2"
          geometry={nodes.Head_m_2.geometry}
          material={materials['Teeth.002']}
          skeleton={nodes.Head_m_2.skeleton}
          morphTargetDictionary={nodes.Head_m_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="Head_m_3"
          geometry={nodes.Head_m_3.geometry}
          material={materials['Eyelash.001']}
          skeleton={nodes.Head_m_3.skeleton}
          morphTargetDictionary={nodes.Head_m_3.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_3.morphTargetInfluences}
        />
        <skinnedMesh
          name="Head_m_4"
          geometry={nodes.Head_m_4.geometry}
          material={materials['Eye.002']}
          skeleton={nodes.Head_m_4.skeleton}
          morphTargetDictionary={nodes.Head_m_4.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_4.morphTargetInfluences}
        />
        <skinnedMesh
          name="Head_m_5"
          geometry={nodes.Head_m_5.geometry}
          material={materials['Eyebrow.002']}
          skeleton={nodes.Head_m_5.skeleton}
          morphTargetDictionary={nodes.Head_m_5.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_5.morphTargetInfluences}
        />
        <skinnedMesh
          name="Head_m_6"
          geometry={nodes.Head_m_6.geometry}
          material={materials['Nose.002']}
          skeleton={nodes.Head_m_6.skeleton}
          morphTargetDictionary={nodes.Head_m_6.morphTargetDictionary}
          morphTargetInfluences={nodes.Head_m_6.morphTargetInfluences}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/static/models/Avatar_temp.glb')
