/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { AnimationMixer } from "three";
import { useLoader } from "@react-three/fiber";
import GUI from "lil-gui";
import { FBXLoader } from "three/examples/jsm/loaders/FBXLoader";
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect, useState } from "react";

export default function Model({ ...props }) {
  //const model = useLoader(FBXLoader, 'static/models/AvatarPreset_Ani.fbx');
  const model = useLoader(FBXLoader, "static/models/Avatar_TPose_22.04.26.fbx");
  const head = model.getObjectByName("Head_m");

  model.position.set(0, -9.5, 0);

  model.scale.set(0.06, 0.06, 0.06);

  return <primitive object={model} />;
}
