/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect, useState, useMemo } from "react";
import useStore from "../../store/UseStore";
import { observer } from "mobx-react";

function Model({ ...props }) {
  const { smplify_store } = useStore();

  const model = useLoader(GLTFLoader, smplify_store.obj_path).scene;

  return <primitive object={model}></primitive>;
}

export default observer(Model);
